services:

  download:
    profiles: ["download"]
    build:
      context: .
      dockerfile: dockerfiles/download-dockerfile

    volumes:
      - ./model:/model/

    environment:
      VOICE_NAME: af_bella

  cpu:
    profiles: ["cpu"]
    build: 
      context: .
      dockerfile: dockerfiles/cpu-dockerfile

    ports:
      - 8888:8888

    volumes:
      - ./model:/model/:ro

  gpu:
    profiles: ["gpu"]
    build: 
      context: .
      dockerfile: dockerfiles/gpu-dockerfile

    ports:
      - 8888:8888

    volumes:
      - ./model:/model/:ro

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]